import type { Metadata } from "next";
import Link from "next/link";
import { MarketingHeader, MarketingFooter } from "@/components/marketing/MarketingChrome";
import { MARKETING_BASE_STYLE } from "@/components/marketing/marketing-base-style";
import {
  SoftwareApplicationJsonLd,
  FaqJsonLd,
  BreadcrumbJsonLd,
  type FaqItem,
} from "@/components/marketing/StructuredData";
import { getMarketingRoute, buildMarketingMetadata } from "@/components/marketing/marketing-routes";

const route = getMarketingRoute("/ai-accounting")!;

export const metadata: Metadata = buildMarketingMetadata(route);

const FAQ_ITEMS: FaqItem[] = [
  {
    question: "What makes accounting software \"AI accounting software\"?",
    answer:
      "Two different things get called that. Some tools add a chat assistant on top of reports that were already generated by a normal ledger — the AI answers questions about numbers it didn't help produce. Others, like Finloraq, run AI directly against the ledger: agents watch postings as they happen, flag anomalies, draft entries and explanations, and a person approves before anything is recorded. The distinction matters because only the second kind can tell you why a number moved, not just what it currently is.",
  },
  {
    question: "Can AI post journal entries without a person approving them?",
    answer:
      "In Finloraq, no. AI agents draft and recommend — an invoice categorization, a reconciling entry, a collections reminder — but nothing posts to the ledger until a person approves it. Once an entry is posted and reconciled, it's immutable, and every change is captured in an audit trail. That split (AI proposes, a human disposes) is what keeps AI accounting from becoming a black box.",
  },
  {
    question: "Does AI accounting software replace a bookkeeper or accountant?",
    answer:
      "It replaces the repetitive parts of the job — matching transactions, flagging duplicates, chasing overdue invoices, drafting the first pass of a close — not the judgment calls. Accountants using Finloraq spend less time on data entry and more time reviewing what the AI already assembled, which is a different job, not no job.",
  },
  {
    question: "Is AI-generated accounting data accurate enough to trust?",
    answer:
      "Only if it's built on real double-entry bookkeeping underneath, not a language model doing arithmetic. Finloraq's AI layer sits on top of a standard general ledger, P&L, balance sheet and AR/AP — the AI explains and drafts against that structured, auditable data, it doesn't invent numbers from a prompt.",
  },
];

export default function AiAccountingPage() {
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: MARKETING_BASE_STYLE }} />
      <SoftwareApplicationJsonLd
        name="Finloraq AI Accounting"
        description={route.description}
        url={route.path}
        category="FinanceApplication"
      />
      <BreadcrumbJsonLd items={[{ name: "Home", path: "/" }, { name: "AI Accounting", path: route.path }]} />
      <FaqJsonLd items={FAQ_ITEMS} />

      <div id="fm-root">
        <MarketingHeader currentPath={route.path} />

        <section className="hero">
          <div className="wrap">
            <div className="breadcrumb">
              <Link href="/">Home</Link> / AI Accounting
            </div>
            <div className="eyebrow on-navy">AI Accounting Software</div>
            <h1 style={{ marginTop: 14 }}>
              AI accounting that&apos;s still <span>real accounting.</span>
            </h1>
            <p className="lead">
              Most &quot;AI accounting&quot; tools are a chat window sitting on top of a dashboard someone
              else&apos;s software already built. Finloraq runs AI directly against a real double-entry
              ledger — so it can tell you not just what your numbers are, but why they moved and
              what to do about it.
            </p>
            <div className="cta-row">
              <Link className="btn btn-primary" href="/register">
                Start Free
              </Link>
              <Link className="btn btn-ghost on-navy" href="/#demo">
                See the Live Demo
              </Link>
            </div>
          </div>
        </section>

        <section className="canvas">
          <div className="wrap">
            <div className="sec-head center">
              <div className="eyebrow">The problem with most &quot;AI accounting&quot;</div>
              <h2 style={{ marginTop: 12 }}>AI on top of a dashboard isn&apos;t AI accounting.</h2>
              <p>
                A chatbot that summarizes reports is useful, but it&apos;s reading output — it has no
                view into how a number was actually produced, and no way to act on what it finds.
                Real AI accounting has to sit inside the ledger, not beside it.
              </p>
            </div>
            <div className="feature-grid">
              <div className="feature-card">
                <div className="glyph">01</div>
                <h3>It reads the ledger, not just the report</h3>
                <p>
                  Finloraq&apos;s agents see individual postings, invoices, bills and bank lines — the
                  same data your books are actually built from — not a pre-summarized dashboard.
                </p>
              </div>
              <div className="feature-card">
                <div className="glyph">02</div>
                <h3>It drafts, it doesn&apos;t decide</h3>
                <p>
                  Categorizations, reconciling entries and reminders come back as drafts. A person
                  reviews and approves before anything posts — nothing is silently recorded.
                </p>
              </div>
              <div className="feature-card">
                <div className="glyph">03</div>
                <h3>It explains the &quot;why,&quot; not just the &quot;what&quot;</h3>
                <p>
                  Instead of a static chart, you get a plain answer: which supplier&apos;s cost rose,
                  which customer is overdue, which expense line is driving the change.
                </p>
              </div>
              <div className="feature-card">
                <div className="glyph">04</div>
                <h3>Posted records stay immutable</h3>
                <p>
                  Once an entry is posted and reconciled, it doesn&apos;t quietly change later. Every
                  edit after that point is a new, audited entry — the way real bookkeeping works.
                </p>
              </div>
              <div className="feature-card">
                <div className="glyph">05</div>
                <h3>Built on standard double-entry</h3>
                <p>
                  General ledger, P&amp;L, balance sheet, AR/AP and multi-currency are the
                  foundation — the same structure any accountant or auditor already expects.
                </p>
              </div>
              <div className="feature-card">
                <div className="glyph">06</div>
                <h3>Every AI action is logged</h3>
                <p>
                  What the AI suggested, when, and who approved it is part of the audit trail —
                  not a black box you have to trust blind.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="canvas-2">
          <div className="wrap">
            <div className="sec-head">
              <div className="eyebrow">How it works</div>
              <h2 style={{ marginTop: 12 }}>From a raw transaction to an approved entry.</h2>
            </div>
            <div className="step-list">
              <div className="step">
                <div className="n">1</div>
                <div>
                  <h3>Record</h3>
                  <p>
                    Invoices, bills, banking and payroll data are captured with full double-entry
                    accuracy — the same foundation any accounting system needs to be trustworthy.
                  </p>
                </div>
              </div>
              <div className="step">
                <div className="n">2</div>
                <div>
                  <h3>Understand</h3>
                  <p>
                    AI agents surface what happened this week or month without you digging through
                    reports — an overdue invoice, a cost spike, a reconciliation mismatch.
                  </p>
                </div>
              </div>
              <div className="step">
                <div className="n">3</div>
                <div>
                  <h3>Draft</h3>
                  <p>
                    The relevant agent — AP, AR, Cash, Close, Tax or CFO — prepares the entry,
                    categorization or reminder, with its reasoning attached.
                  </p>
                </div>
              </div>
              <div className="step">
                <div className="n">4</div>
                <div>
                  <h3>Approve</h3>
                  <p>
                    You review and approve. Only then does it post — and from that point it&apos;s part
                    of your permanent, auditable books.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="canvas">
          <div className="wrap">
            <div className="sec-head">
              <div className="eyebrow">Comparing approaches</div>
              <h2 style={{ marginTop: 12 }}>Where each approach actually sits.</h2>
            </div>
            <div className="compare-wrap">
              <table className="compare">
                <thead>
                  <tr>
                    <th>Approach</th>
                    <th>Real double-entry ledger</th>
                    <th>AI drafts &amp; explains</th>
                    <th>Human approval required</th>
                    <th>Full audit trail</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Manual spreadsheets</td>
                    <td className="no">Depends on discipline</td>
                    <td className="no">No</td>
                    <td className="yes">Implicitly, yes</td>
                    <td className="no">Rarely</td>
                  </tr>
                  <tr>
                    <td>Traditional accounting software</td>
                    <td className="yes">Yes</td>
                    <td className="no">No</td>
                    <td className="yes">Yes</td>
                    <td className="yes">Yes</td>
                  </tr>
                  <tr>
                    <td>Dashboard-only &quot;AI&quot; add-ons</td>
                    <td className="no">Reads someone else&apos;s ledger</td>
                    <td className="yes">Summarizes, doesn&apos;t act</td>
                    <td className="no">Nothing to approve</td>
                    <td className="no">No</td>
                  </tr>
                  <tr>
                    <td>Finloraq</td>
                    <td className="yes">Yes</td>
                    <td className="yes">Yes</td>
                    <td className="yes">Yes</td>
                    <td className="yes">Yes</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div className="inline-links">
              <Link href="/ai-cfo">See how the AI CFO agent works →</Link>
              <Link href="/cash-flow-forecasting">Cash flow forecasting →</Link>
              <Link href="/guides">Browse all guides →</Link>
            </div>
          </div>
        </section>

        <section className="canvas-2" id="ai-accounting-faq">
          <div className="wrap">
            <div className="sec-head" style={{ marginBottom: 8 }}>
              <div className="eyebrow">FAQ</div>
              <h2 style={{ marginTop: 12 }}>Questions about AI accounting, answered plainly.</h2>
            </div>
            <div style={{ marginTop: 28, display: "flex", flexDirection: "column", gap: 22 }}>
              {FAQ_ITEMS.map((item) => (
                <div key={item.question}>
                  <h3 style={{ fontSize: 16, fontWeight: 800 }}>{item.question}</h3>
                  <p style={{ marginTop: 8, fontSize: 14, color: "var(--ink-muted)", lineHeight: 1.65, maxWidth: "70ch" }}>
                    {item.answer}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="final-cta">
          <div className="wrap">
            <h2>See what your own books look like with AI actually watching them.</h2>
            <p>No registration required to try the live demo.</p>
            <div className="cta-row">
              <Link className="btn btn-primary" href="/register">
                Start Free
              </Link>
              <Link className="btn btn-ghost on-navy" href="/#demo">
                Explore the Demo
              </Link>
            </div>
          </div>
        </section>

        <MarketingFooter />
      </div>
    </>
  );
}
